services:
  nest-backend:
    container_name: nest-backend
    build:
      dockerfile: ./packages/nest-backend/Dockerfile
    ports:
      - "4010:3000"
    develop:
      watch:
        - action: sync
          path: ./packages/nest-backend
          target: /app/packages/nest-backend
          ignore:
            - node_modules/
        - action: rebuild
          path: ./packages/nest-backend/package.json

  hono-backend:
    container_name: hono-backend
    build:
      dockerfile: ./packages/hono-backend/Dockerfile
    ports:
      - "4011:3000"
    develop:
      watch:
        - action: sync
          path: ./packages/hono-backend
          target: /app/packages/hono-backend
          ignore:
            - node_modules/
        - action: rebuild
          path: ./packages/hono-backend/package.json

  next-frontend:
    container_name: next-frontend
    build:
      dockerfile: ./packages/next-frontend/Dockerfile
    ports:
      - "4000:3000"
    develop:
      watch:
        - action: sync
          path: ./packages/next-frontend
          target: /app/packages/next-frontend
          ignore:
            - node_modules/
        - action: rebuild
          path: ./packages/next-frontend/package.json

  nuxt-frontend:
    container_name: nuxt-frontend
    build:
      dockerfile: ./packages/nuxt-frontend/Dockerfile
    ports:
      - "4001:3000"
    develop:
      watch:
        - action: sync
          path: ./packages/nuxt-frontend
          target: /app/packages/nuxt-frontend
          ignore:
            - node_modules/
        - action: rebuild
          path: ./packages/nuxt-frontend/package.json
