export const API_ERROR = {
	EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
	EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
	INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
	INVALID_SESSION: "INVALID_SESSION",
	INVALID_TOKEN: "INVALID_TOKEN",
	POST_NOT_FOUND: "POST_NOT_FOUND",
	SESSION_EXPIRED: "SESSION_EXPIRED",
	USER_NOT_FOUND: "USER_NOT_FOUND",
} as const;
